<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EjWGx9YService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ejWGx9Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ejWGx9Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'degreeRepository' => ['privates', 'App\\Repository\\DegreeRepository', 'getDegreeRepositoryService', true],
        ], [
            'degreeRepository' => 'App\\Repository\\DegreeRepository',
        ]);
    }
}
