<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JFGHs3AService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JFGHs3A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JFGHs3A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
            'civilityRepository' => ['privates', 'App\\Repository\\CivilityRepository', 'getCivilityRepositoryService', true],
            'degreeRepository' => ['privates', 'App\\Repository\\DegreeRepository', 'getDegreeRepositoryService', true],
            'educationRepository' => ['privates', 'App\\Repository\\EducationRepository', 'getEducationRepositoryService', true],
            'fieldOfStudyRepository' => ['privates', 'App\\Repository\\FieldOfStudyRepository', 'getFieldOfStudyRepositoryService', true],
            'internshipRepository' => ['privates', 'App\\Repository\\InternshipRepository', 'getInternshipRepositoryService', true],
            'levelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
            'maritalStatusRepository' => ['privates', 'App\\Repository\\MaritalStatusRepository', 'getMaritalStatusRepositoryService', true],
            'positionRepository' => ['privates', 'App\\Repository\\PositionRepository', 'getPositionRepositoryService', true],
            'skillRepository' => ['privates', 'App\\Repository\\SkillRepository', 'getSkillRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'workExperienceRepository' => ['privates', 'App\\Repository\\WorkExperienceRepository', 'getWorkExperienceRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
            'civilityRepository' => 'App\\Repository\\CivilityRepository',
            'degreeRepository' => 'App\\Repository\\DegreeRepository',
            'educationRepository' => 'App\\Repository\\EducationRepository',
            'fieldOfStudyRepository' => 'App\\Repository\\FieldOfStudyRepository',
            'internshipRepository' => 'App\\Repository\\InternshipRepository',
            'levelRepository' => 'App\\Repository\\LevelRepository',
            'maritalStatusRepository' => 'App\\Repository\\MaritalStatusRepository',
            'positionRepository' => 'App\\Repository\\PositionRepository',
            'skillRepository' => 'App\\Repository\\SkillRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'workExperienceRepository' => 'App\\Repository\\WorkExperienceRepository',
        ]);
    }
}
