<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SY0exvSService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.sY0exvS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sY0exvS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'educationRepository' => ['privates', 'App\\Repository\\EducationRepository', 'getEducationRepositoryService', true],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'engagementRepository' => ['privates', 'App\\Repository\\EngagementRepository', 'getEngagementRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'internshipRepository' => ['privates', 'App\\Repository\\InternshipRepository', 'getInternshipRepositoryService', true],
            'otherInfoRepository' => ['privates', 'App\\Repository\\OtherInfoRepository', 'getOtherInfoRepositoryService', true],
            'profileRepository' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
            'workExperienceRepository' => ['privates', 'App\\Repository\\WorkExperienceRepository', 'getWorkExperienceRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
            'documentRepository' => 'App\\Repository\\DocumentRepository',
            'educationRepository' => 'App\\Repository\\EducationRepository',
            'emailService' => 'App\\Service\\EmailService',
            'engagementRepository' => 'App\\Repository\\EngagementRepository',
            'entityManager' => '?',
            'internshipRepository' => 'App\\Repository\\InternshipRepository',
            'otherInfoRepository' => 'App\\Repository\\OtherInfoRepository',
            'profileRepository' => 'App\\Repository\\ProfileRepository',
            'repository' => 'App\\Repository\\JobApplicationRepository',
            'workExperienceRepository' => 'App\\Repository\\WorkExperienceRepository',
        ]);
    }
}
