<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultEntityManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine.orm.default_entity_manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['doctrine.orm.default_entity_manager'] = $container->createProxy('EntityManagerGhost6410e2e', static fn () => \EntityManagerGhost6410e2e::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        $a = new \Doctrine\ORM\Configuration();

        $b = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $b->addDriver(new \Doctrine\ORM\Mapping\Driver\AttributeDriver([(\dirname(__DIR__, 4).'/src/Entity')], true), 'App\\Entity');

        $a->setEntityNamespaces(['App' => 'App\\Entity']);
        $a->setMetadataCache(new \Symfony\Component\Cache\Adapter\PhpArrayAdapter(($container->targetDir.''.'/doctrine/orm/default_metadata.php'), new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $a->setQueryCache(($container->privates['doctrine.system_cache_pool'] ?? $container->load('getDoctrine_SystemCachePoolService')));
        $a->setResultCache(($container->privates['doctrine.result_cache_pool'] ?? $container->load('getDoctrine_ResultCachePoolService')));
        $a->setMetadataDriverImpl(new \Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver($b, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine.ulid_generator' => ['privates', 'doctrine.ulid_generator', 'getDoctrine_UlidGeneratorService', true],
            'doctrine.uuid_generator' => ['privates', 'doctrine.uuid_generator', 'getDoctrine_UuidGeneratorService', true],
        ], [
            'doctrine.ulid_generator' => '?',
            'doctrine.uuid_generator' => '?',
        ])));
        $a->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $a->setProxyNamespace('Proxies');
        $a->setAutoGenerateProxyClasses(false);
        $a->setSchemaIgnoreClasses([]);
        $a->setClassMetadataFactoryName('Doctrine\\Bundle\\DoctrineBundle\\Mapping\\ClassMetadataFactory');
        $a->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $a->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $a->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $a->setEntityListenerResolver(($container->services['doctrine.orm.default_entity_listener_resolver'] ?? $container->load('getDoctrine_Orm_DefaultEntityListenerResolverService')));
        $a->setLazyGhostObjectEnabled(true);
        $a->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\CertificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
            'App\\Repository\\CivilityRepository' => ['privates', 'App\\Repository\\CivilityRepository', 'getCivilityRepositoryService', true],
            'App\\Repository\\DegreeRepository' => ['privates', 'App\\Repository\\DegreeRepository', 'getDegreeRepositoryService', true],
            'App\\Repository\\DocumentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'App\\Repository\\EducationRepository' => ['privates', 'App\\Repository\\EducationRepository', 'getEducationRepositoryService', true],
            'App\\Repository\\EngagementRepository' => ['privates', 'App\\Repository\\EngagementRepository', 'getEngagementRepositoryService', true],
            'App\\Repository\\FieldOfStudyRepository' => ['privates', 'App\\Repository\\FieldOfStudyRepository', 'getFieldOfStudyRepositoryService', true],
            'App\\Repository\\InternshipRepository' => ['privates', 'App\\Repository\\InternshipRepository', 'getInternshipRepositoryService', true],
            'App\\Repository\\JobApplicationRepository' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
            'App\\Repository\\LevelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
            'App\\Repository\\LocationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
            'App\\Repository\\MaritalStatusRepository' => ['privates', 'App\\Repository\\MaritalStatusRepository', 'getMaritalStatusRepositoryService', true],
            'App\\Repository\\OtherInfoRepository' => ['privates', 'App\\Repository\\OtherInfoRepository', 'getOtherInfoRepositoryService', true],
            'App\\Repository\\PositionRepository' => ['privates', 'App\\Repository\\PositionRepository', 'getPositionRepositoryService', true],
            'App\\Repository\\ProfileRepository' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService', true],
            'App\\Repository\\SkillRepository' => ['privates', 'App\\Repository\\SkillRepository', 'getSkillRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\WorkExperienceRepository' => ['privates', 'App\\Repository\\WorkExperienceRepository', 'getWorkExperienceRepositoryService', true],
        ], [
            'App\\Repository\\CertificationRepository' => '?',
            'App\\Repository\\CivilityRepository' => '?',
            'App\\Repository\\DegreeRepository' => '?',
            'App\\Repository\\DocumentRepository' => '?',
            'App\\Repository\\EducationRepository' => '?',
            'App\\Repository\\EngagementRepository' => '?',
            'App\\Repository\\FieldOfStudyRepository' => '?',
            'App\\Repository\\InternshipRepository' => '?',
            'App\\Repository\\JobApplicationRepository' => '?',
            'App\\Repository\\LevelRepository' => '?',
            'App\\Repository\\LocationRepository' => '?',
            'App\\Repository\\MaritalStatusRepository' => '?',
            'App\\Repository\\OtherInfoRepository' => '?',
            'App\\Repository\\PositionRepository' => '?',
            'App\\Repository\\ProfileRepository' => '?',
            'App\\Repository\\SkillRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
            'App\\Repository\\WorkExperienceRepository' => '?',
        ])));

        $instance = ($lazyLoad->__construct(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')), $a, ($container->privates['doctrine.dbal.default_connection.event_manager'] ?? $container->load('getDoctrine_Dbal_DefaultConnection_EventManagerService'))) && false ?: $lazyLoad);

        (new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))->configure($instance);

        return $instance;
    }
}
