<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldOfStudyTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FieldOfStudyType' shared autowired service.
     *
     * @return \App\Form\FieldOfStudyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FieldOfStudyType'] = new \App\Form\FieldOfStudyType();
    }
}
