<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInternshipTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\InternshipType' shared autowired service.
     *
     * @return \App\Form\InternshipType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\InternshipType'] = new \App\Form\InternshipType();
    }
}
