<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobApplicationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JobApplicationRepository' shared autowired service.
     *
     * @return \App\Repository\JobApplicationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JobApplicationRepository'] = new \App\Repository\JobApplicationRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
