<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLevelRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LevelRepository' shared autowired service.
     *
     * @return \App\Repository\LevelRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LevelRepository'] = new \App\Repository\LevelRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
