<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOtherInfoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OtherInfoRepository' shared autowired service.
     *
     * @return \App\Repository\OtherInfoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OtherInfoRepository'] = new \App\Repository\OtherInfoRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
