<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOtherInfoTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\OtherInfoType' shared autowired service.
     *
     * @return \App\Form\OtherInfoType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\OtherInfoType'] = new \App\Form\OtherInfoType(($container->privates['App\\Repository\\LevelRepository'] ?? $container->load('getLevelRepositoryService')), ($container->privates['App\\Repository\\SkillRepository'] ?? $container->load('getSkillRepositoryService')));
    }
}
