<?php

namespace ContainerIK5IPP1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Back\UserController' shared autowired service.
     *
     * @return \App\Controller\Back\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Back\\UserController'] = $instance = new \App\Controller\Back\UserController(($container->privates['App\\Service\\OracleService'] ?? $container->load('getOracleServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\UserController', $container));

        return $instance;
    }
}
