<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQksNMxService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.wQksNMx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQksNMx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificationRepository' => ['privates', 'App\\Repository\\CertificationRepository', 'getCertificationRepositoryService', true],
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'educationRepository' => ['privates', 'App\\Repository\\EducationRepository', 'getEducationRepositoryService', true],
            'engagementRepository' => ['privates', 'App\\Repository\\EngagementRepository', 'getEngagementRepositoryService', true],
            'internshipRepository' => ['privates', 'App\\Repository\\InternshipRepository', 'getInternshipRepositoryService', true],
            'otherInfoRepository' => ['privates', 'App\\Repository\\OtherInfoRepository', 'getOtherInfoRepositoryService', true],
            'profileRepository' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
            'workExperienceRepository' => ['privates', 'App\\Repository\\WorkExperienceRepository', 'getWorkExperienceRepositoryService', true],
        ], [
            'certificationRepository' => 'App\\Repository\\CertificationRepository',
            'documentRepository' => 'App\\Repository\\DocumentRepository',
            'educationRepository' => 'App\\Repository\\EducationRepository',
            'engagementRepository' => 'App\\Repository\\EngagementRepository',
            'internshipRepository' => 'App\\Repository\\InternshipRepository',
            'otherInfoRepository' => 'App\\Repository\\OtherInfoRepository',
            'profileRepository' => 'App\\Repository\\ProfileRepository',
            'repository' => 'App\\Repository\\JobApplicationRepository',
            'workExperienceRepository' => 'App\\Repository\\WorkExperienceRepository',
        ]);
    }
}
