<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQSIfFvService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.KQSIfFv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQSIfFv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'degreeRepository' => ['privates', 'App\\Repository\\DegreeRepository', 'getDegreeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fieldOfStudyRepository' => ['privates', 'App\\Repository\\FieldOfStudyRepository', 'getFieldOfStudyRepositoryService', true],
            'positionRepository' => ['privates', 'App\\Repository\\PositionRepository', 'getPositionRepositoryService', true],
        ], [
            'degreeRepository' => 'App\\Repository\\DegreeRepository',
            'entityManager' => '?',
            'fieldOfStudyRepository' => 'App\\Repository\\FieldOfStudyRepository',
            'positionRepository' => 'App\\Repository\\PositionRepository',
        ]);
    }
}
