<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEngagementTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\EngagementType' shared autowired service.
     *
     * @return \App\Form\EngagementType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EngagementType'] = new \App\Form\EngagementType(($container->privates['App\\Repository\\PositionRepository'] ?? $container->load('getPositionRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
