<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaritalStatusRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\MaritalStatusRepository' shared autowired service.
     *
     * @return \App\Repository\MaritalStatusRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MaritalStatusRepository'] = new \App\Repository\MaritalStatusRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
