<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaritalStatusTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\MaritalStatusType' shared autowired service.
     *
     * @return \App\Form\MaritalStatusType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MaritalStatusType'] = new \App\Form\MaritalStatusType();
    }
}
