<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOracleServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Service\OracleService' shared autowired service.
     *
     * @return \App\Service\OracleService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\OracleService'] = new \App\Service\OracleService(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));
    }
}
