<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ProfileType' shared autowired service.
     *
     * @return \App\Form\ProfileType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProfileType'] = new \App\Form\ProfileType(($container->privates['App\\Repository\\CivilityRepository'] ?? $container->load('getCivilityRepositoryService')), ($container->privates['App\\Repository\\MaritalStatusRepository'] ?? $container->load('getMaritalStatusRepositoryService')));
    }
}
