<?php

namespace ContainerSPB7uTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStateControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Back\StateController' shared autowired service.
     *
     * @return \App\Controller\Back\StateController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Back\\StateController'] = $instance = new \App\Controller\Back\StateController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\StateController', $container));

        return $instance;
    }
}
