<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIK5IPP1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIK5IPP1/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIK5IPP1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIK5IPP1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIK5IPP1\App_KernelProdContainer([
    'container.build_hash' => 'IK5IPP1',
    'container.build_id' => '0d62b9f6',
    'container.build_time' => 1779801851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIK5IPP1');
