<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPtBEXn\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPtBEXn/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIPtBEXn.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIPtBEXn\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIPtBEXn\App_KernelProdContainer([
    'container.build_hash' => 'IPtBEXn',
    'container.build_id' => 'fa85c9b8',
    'container.build_time' => 1781529127,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPtBEXn');
