<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'birth_date' => [parent::class, 'birth_date', null],
        "\0".parent::class."\0".'certifications' => [parent::class, 'certifications', null],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null],
        "\0".parent::class."\0".'document' => [parent::class, 'document', null],
        "\0".parent::class."\0".'education' => [parent::class, 'education', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'engagement' => [parent::class, 'engagement', null],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null],
        "\0".parent::class."\0".'hasSubmittedApplication' => [parent::class, 'hasSubmittedApplication', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'internships' => [parent::class, 'internships', null],
        "\0".parent::class."\0".'is_deleted' => [parent::class, 'is_deleted', null],
        "\0".parent::class."\0".'jobApplication' => [parent::class, 'jobApplication', null],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null],
        "\0".parent::class."\0".'otherInfo' => [parent::class, 'otherInfo', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null],
        "\0".parent::class."\0".'profile' => [parent::class, 'profile', null],
        "\0".parent::class."\0".'reference_position' => [parent::class, 'reference_position', null],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'workExperiences' => [parent::class, 'workExperiences', null],
        'birth_date' => [parent::class, 'birth_date', null],
        'certifications' => [parent::class, 'certifications', null],
        'cin' => [parent::class, 'cin', null],
        'document' => [parent::class, 'document', null],
        'education' => [parent::class, 'education', null],
        'email' => [parent::class, 'email', null],
        'engagement' => [parent::class, 'engagement', null],
        'first_name' => [parent::class, 'first_name', null],
        'hasSubmittedApplication' => [parent::class, 'hasSubmittedApplication', null],
        'id' => [parent::class, 'id', null],
        'internships' => [parent::class, 'internships', null],
        'is_deleted' => [parent::class, 'is_deleted', null],
        'jobApplication' => [parent::class, 'jobApplication', null],
        'last_name' => [parent::class, 'last_name', null],
        'otherInfo' => [parent::class, 'otherInfo', null],
        'password' => [parent::class, 'password', null],
        'plainPassword' => [parent::class, 'plainPassword', null],
        'profile' => [parent::class, 'profile', null],
        'reference_position' => [parent::class, 'reference_position', null],
        'resetToken' => [parent::class, 'resetToken', null],
        'roles' => [parent::class, 'roles', null],
        'workExperiences' => [parent::class, 'workExperiences', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
