-- Create sequences and triggers for all tables

-- Table: EREC_USER
CREATE SEQUENCE EREC_USER_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_USER_BEFORE_INSERT
BEFORE INSERT ON EREC_USER
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_USER_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_CERTIFICATION
CREATE SEQUENCE EREC_CERT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_CERT_BI
BEFORE INSERT ON EREC_CERTIFICATION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_CERT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_CIVILITY
CREATE SEQUENCE EREC_CIV_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_CIV_BI
BEFORE INSERT ON EREC_CIVILITY
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_CIV_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_DEGREE
CREATE SEQUENCE EREC_DEG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_DEG_BI
BEFORE INSERT ON EREC_DEGREE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_DEG_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_DOCUMENT
CREATE SEQUENCE EREC_DOC_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_DOC_BI
BEFORE INSERT ON EREC_DOCUMENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_DOC_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_EDUCATION
CREATE SEQUENCE EREC_EDU_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_EDU_BI
BEFORE INSERT ON EREC_EDUCATION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_EDU_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_ENGAGEMENT
CREATE SEQUENCE EREC_ENG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_ENG_BI
BEFORE INSERT ON EREC_ENGAGEMENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_ENG_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_FIELD_OF_STUDY
CREATE SEQUENCE EREC_FOS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_FOS_BI
BEFORE INSERT ON EREC_FIELD_OF_STUDY
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_FOS_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_INTERNSHIP
CREATE SEQUENCE EREC_INT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_INT_BI
BEFORE INSERT ON EREC_INTERNSHIP
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_INT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_JOB_APPLICATION
CREATE SEQUENCE EREC_JOBAPP_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_JOBAPP_BI
BEFORE INSERT ON EREC_JOB_APPLICATION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_JOBAPP_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_LEVEL
CREATE SEQUENCE EREC_LVL_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_LVL_BI
BEFORE INSERT ON EREC_LEVEL
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_LVL_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_LOCATION
CREATE SEQUENCE EREC_LOC_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_LOC_BI
BEFORE INSERT ON EREC_LOCATION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_LOC_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_MARITAL_STATUS
CREATE SEQUENCE EREC_MARSTAT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_MARSTAT_BI
BEFORE INSERT ON EREC_MARITAL_STATUS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_MARSTAT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_OTHER_INFO
CREATE SEQUENCE EREC_OTHINFO_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_OTHINFO_BI
BEFORE INSERT ON EREC_OTHER_INFO
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_OTHINFO_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_POSITION
CREATE SEQUENCE EREC_POS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_POS_BI
BEFORE INSERT ON EREC_POSITION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_POS_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_PROFILE
CREATE SEQUENCE EREC_PROF_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_PROF_BI
BEFORE INSERT ON EREC_PROFILE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_PROF_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_SKILL
CREATE SEQUENCE EREC_SKILL_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_SKILL_BI
BEFORE INSERT ON EREC_SKILL
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_SKILL_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table: EREC_WORK_EXPERIENCE
CREATE SEQUENCE EREC_WORKEXP_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_WORKEXP_BI
BEFORE INSERT ON EREC_WORK_EXPERIENCE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_WORKEXP_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table campaign
CREATE SEQUENCE EREC_CAMPAIGN_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE OR REPLACE TRIGGER EREC_CAMPAIGN_BEFORE_INSERT
BEFORE INSERT ON EREC_CAMPAIGN
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_CAMPAIGN_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table user _ poste
CREATE SEQUENCE EREC_USER_POSITION_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE OR REPLACE TRIGGER EREC_USER_POS_BEFORE_INSERT
BEFORE INSERT ON EREC_USER_POSITION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_USER_POSITION_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

-- Table type de contrat
CREATE SEQUENCE EREC_CONTRACT_TYPE_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE OR REPLACE TRIGGER EREC_CON_TYPE_BEFORE_INSERT
BEFORE INSERT ON EREC_CONTRACT_TYPE
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT EREC_CONTRACT_TYPE_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
