<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9oFOoFzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9oFOoFz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9oFOoFz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'levelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
        ], [
            'levelRepository' => 'App\\Repository\\LevelRepository',
        ]);
    }
}
