<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WX5mtoWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WX5mtoW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WX5mtoW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'internshipRepository' => ['privates', 'App\\Repository\\InternshipRepository', 'getInternshipRepositoryService', true],
        ], [
            'internshipRepository' => 'App\\Repository\\InternshipRepository',
        ]);
    }
}
