<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Back\CertificationController' shared autowired service.
     *
     * @return \App\Controller\Back\CertificationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Back/CertificationController.php';

        $container->services['App\\Controller\\Back\\CertificationController'] = $instance = new \App\Controller\Back\CertificationController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\CertificationController', $container));

        return $instance;
    }
}
