<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEngagementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Front\EngagementController' shared autowired service.
     *
     * @return \App\Controller\Front\EngagementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Front/EngagementController.php';

        $container->services['App\\Controller\\Front\\EngagementController'] = $instance = new \App\Controller\Front\EngagementController(($container->privates['App\\Service\\OracleService'] ?? $container->load('getOracleServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Front\\EngagementController', $container));

        return $instance;
    }
}
