<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ExcelExportService' shared autowired service.
     *
     * @return \App\Service\ExcelExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ExcelExportService.php';

        return $container->privates['App\\Service\\ExcelExportService'] = new \App\Service\ExcelExportService();
    }
}
