<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldOfStudyTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FieldOfStudyType' shared autowired service.
     *
     * @return \App\Form\FieldOfStudyType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FieldOfStudyType.php';

        return $container->privates['App\\Form\\FieldOfStudyType'] = new \App\Form\FieldOfStudyType();
    }
}
