<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOtherInfoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OtherInfoType' shared autowired service.
     *
     * @return \App\Form\OtherInfoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/OtherInfoType.php';

        return $container->privates['App\\Form\\OtherInfoType'] = new \App\Form\OtherInfoType(($container->privates['App\\Repository\\LevelRepository'] ?? $container->load('getLevelRepositoryService')), ($container->privates['App\\Repository\\SkillRepository'] ?? $container->load('getSkillRepositoryService')));
    }
}
