<?php

namespace ContainerZ6xz6tU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UtilsCommand' shared autowired service.
     *
     * @return \App\Command\UtilsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UtilsCommand.php';

        $container->privates['App\\Command\\UtilsCommand'] = $instance = new \App\Command\UtilsCommand(($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('app:utils-cmd');

        return $instance;
    }
}
