<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSPB7uTv\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSPB7uTv/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerSPB7uTv.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerSPB7uTv\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerSPB7uTv\App_KernelDevContainer([
    'container.build_hash' => 'SPB7uTv',
    'container.build_id' => 'e10c211e',
    'container.build_time' => 1748420732,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSPB7uTv');
