<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6xz6tU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6xz6tU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6xz6tU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6xz6tU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6xz6tU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z6xz6tU',
    'container.build_id' => '33c6abd0',
    'container.build_time' => 1750762123,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6xz6tU');
