<?php

namespace ContainerOsUHy5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IMw3pHyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iMw3pHy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iMw3pHy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excelExportService' => ['privates', 'App\\Service\\ExcelExportService', 'getExcelExportServiceService', true],
            'positionRepository' => ['privates', 'App\\Repository\\PositionRepository', 'getPositionRepositoryService', true],
        ], [
            'excelExportService' => 'App\\Service\\ExcelExportService',
            'positionRepository' => 'App\\Repository\\PositionRepository',
        ]);
    }
}
