<?php

namespace ContainerOsUHy5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEngagementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EngagementType' shared autowired service.
     *
     * @return \App\Form\EngagementType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EngagementType.php';

        return $container->privates['App\\Form\\EngagementType'] = new \App\Form\EngagementType(($container->privates['App\\Repository\\PositionRepository'] ?? $container->load('getPositionRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
