<?php

namespace ContainerOsUHy5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\CertificationType' => ['privates', 'App\\Form\\CertificationType', 'getCertificationTypeService', true],
            'App\\Form\\CivilityType' => ['privates', 'App\\Form\\CivilityType', 'getCivilityTypeService', true],
            'App\\Form\\DegreeType' => ['privates', 'App\\Form\\DegreeType', 'getDegreeTypeService', true],
            'App\\Form\\DocumentType' => ['privates', 'App\\Form\\DocumentType', 'getDocumentTypeService', true],
            'App\\Form\\EducationType' => ['privates', 'App\\Form\\EducationType', 'getEducationTypeService', true],
            'App\\Form\\EngagementType' => ['privates', 'App\\Form\\EngagementType', 'getEngagementTypeService', true],
            'App\\Form\\FieldOfStudyType' => ['privates', 'App\\Form\\FieldOfStudyType', 'getFieldOfStudyTypeService', true],
            'App\\Form\\ForgotPasswordType' => ['privates', 'App\\Form\\ForgotPasswordType', 'getForgotPasswordTypeService', true],
            'App\\Form\\InternshipType' => ['privates', 'App\\Form\\InternshipType', 'getInternshipTypeService', true],
            'App\\Form\\JobApplicationType' => ['privates', 'App\\Form\\JobApplicationType', 'getJobApplicationTypeService', true],
            'App\\Form\\LevelType' => ['privates', 'App\\Form\\LevelType', 'getLevelTypeService', true],
            'App\\Form\\MaritalStatusType' => ['privates', 'App\\Form\\MaritalStatusType', 'getMaritalStatusTypeService', true],
            'App\\Form\\OtherInfoType' => ['privates', 'App\\Form\\OtherInfoType', 'getOtherInfoTypeService', true],
            'App\\Form\\PositionType' => ['privates', 'App\\Form\\PositionType', 'getPositionTypeService', true],
            'App\\Form\\ProfileType' => ['privates', 'App\\Form\\ProfileType', 'getProfileTypeService', true],
            'App\\Form\\RegistrationType' => ['privates', 'App\\Form\\RegistrationType', 'getRegistrationTypeService', true],
            'App\\Form\\ResetPasswordType' => ['privates', 'App\\Form\\ResetPasswordType', 'getResetPasswordTypeService', true],
            'App\\Form\\SkillType' => ['privates', 'App\\Form\\SkillType', 'getSkillTypeService', true],
            'App\\Form\\UserPasswordType' => ['privates', 'App\\Form\\UserPasswordType', 'getUserPasswordTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'App\\Form\\WorkExperienceType' => ['privates', 'App\\Form\\WorkExperienceType', 'getWorkExperienceTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\CertificationType' => '?',
            'App\\Form\\CivilityType' => '?',
            'App\\Form\\DegreeType' => '?',
            'App\\Form\\DocumentType' => '?',
            'App\\Form\\EducationType' => '?',
            'App\\Form\\EngagementType' => '?',
            'App\\Form\\FieldOfStudyType' => '?',
            'App\\Form\\ForgotPasswordType' => '?',
            'App\\Form\\InternshipType' => '?',
            'App\\Form\\JobApplicationType' => '?',
            'App\\Form\\LevelType' => '?',
            'App\\Form\\MaritalStatusType' => '?',
            'App\\Form\\OtherInfoType' => '?',
            'App\\Form\\PositionType' => '?',
            'App\\Form\\ProfileType' => '?',
            'App\\Form\\RegistrationType' => '?',
            'App\\Form\\ResetPasswordType' => '?',
            'App\\Form\\SkillType' => '?',
            'App\\Form\\UserPasswordType' => '?',
            'App\\Form\\UserType' => '?',
            'App\\Form\\WorkExperienceType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ??= new \Symfony\Component\Form\Extension\Core\Type\TransformationFailureExtension(NULL));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 4 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
            yield 5 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? self::getDataCollector_FormService($container))));
    }
}
