<?php

namespace ContainerOsUHy5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaritalStatusControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Back\MaritalStatusController' shared autowired service.
     *
     * @return \App\Controller\Back\MaritalStatusController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Back/MaritalStatusController.php';

        $container->services['App\\Controller\\Back\\MaritalStatusController'] = $instance = new \App\Controller\Back\MaritalStatusController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\MaritalStatusController', $container));

        return $instance;
    }
}
