<?php

namespace ContainerOsUHy5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SkillType' shared autowired service.
     *
     * @return \App\Form\SkillType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SkillType.php';

        return $container->privates['App\\Form\\SkillType'] = new \App\Form\SkillType();
    }
}
