<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Education extends \App\Entity\Education implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'degree' => [parent::class, 'degree', null],
        "\0".parent::class."\0".'degreeFilename' => [parent::class, 'degreeFilename', null],
        "\0".parent::class."\0".'field_of_study' => [parent::class, 'field_of_study', null],
        "\0".parent::class."\0".'graduation_year' => [parent::class, 'graduation_year', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'other_field_of_study' => [parent::class, 'other_field_of_study', null],
        "\0".parent::class."\0".'specialty' => [parent::class, 'specialty', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'degree' => [parent::class, 'degree', null],
        'degreeFilename' => [parent::class, 'degreeFilename', null],
        'field_of_study' => [parent::class, 'field_of_study', null],
        'graduation_year' => [parent::class, 'graduation_year', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'other_field_of_study' => [parent::class, 'other_field_of_study', null],
        'specialty' => [parent::class, 'specialty', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
