<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Certification extends \App\Entity\Certification implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'certification' => [parent::class, 'certification', null],
        "\0".parent::class."\0".'certificationFilename' => [parent::class, 'certificationFilename', null],
        "\0".parent::class."\0".'certification_year' => [parent::class, 'certification_year', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'institution' => [parent::class, 'institution', null],
        "\0".parent::class."\0".'specialty' => [parent::class, 'specialty', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'certification' => [parent::class, 'certification', null],
        'certificationFilename' => [parent::class, 'certificationFilename', null],
        'certification_year' => [parent::class, 'certification_year', null],
        'id' => [parent::class, 'id', null],
        'institution' => [parent::class, 'institution', null],
        'specialty' => [parent::class, 'specialty', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
