<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobApplication extends \App\Entity\JobApplication implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'primary_location' => [parent::class, 'primary_location', null],
        "\0".parent::class."\0".'secondary_location' => [parent::class, 'secondary_location', null],
        "\0".parent::class."\0".'tertiary_location' => [parent::class, 'tertiary_location', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'id' => [parent::class, 'id', null],
        'primary_location' => [parent::class, 'primary_location', null],
        'secondary_location' => [parent::class, 'secondary_location', null],
        'tertiary_location' => [parent::class, 'tertiary_location', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
