<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Engagement extends \App\Entity\Engagement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'date_engagement' => [parent::class, 'date_engagement', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'second_position' => [parent::class, 'second_position', null],
        "\0".parent::class."\0".'third_position' => [parent::class, 'third_position', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'city' => [parent::class, 'city', null],
        'date_engagement' => [parent::class, 'date_engagement', null],
        'id' => [parent::class, 'id', null],
        'second_position' => [parent::class, 'second_position', null],
        'third_position' => [parent::class, 'third_position', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
