<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Internship extends \App\Entity\Internship implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'internship_year' => [parent::class, 'internship_year', null],
        "\0".parent::class."\0".'organization' => [parent::class, 'organization', null],
        "\0".parent::class."\0".'theme' => [parent::class, 'theme', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'duration' => [parent::class, 'duration', null],
        'id' => [parent::class, 'id', null],
        'internship_year' => [parent::class, 'internship_year', null],
        'organization' => [parent::class, 'organization', null],
        'theme' => [parent::class, 'theme', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
