<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OtherInfo extends \App\Entity\OtherInfo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'english_reading_level' => [parent::class, 'english_reading_level', null],
        "\0".parent::class."\0".'english_speaking_level' => [parent::class, 'english_speaking_level', null],
        "\0".parent::class."\0".'english_writing_level' => [parent::class, 'english_writing_level', null],
        "\0".parent::class."\0".'french_reading_level' => [parent::class, 'french_reading_level', null],
        "\0".parent::class."\0".'french_speaking_level' => [parent::class, 'french_speaking_level', null],
        "\0".parent::class."\0".'french_writing_level' => [parent::class, 'french_writing_level', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'malagasy_reading_level' => [parent::class, 'malagasy_reading_level', null],
        "\0".parent::class."\0".'malagasy_speaking_level' => [parent::class, 'malagasy_speaking_level', null],
        "\0".parent::class."\0".'malagasy_writing_level' => [parent::class, 'malagasy_writing_level', null],
        "\0".parent::class."\0".'microsoft_access_level' => [parent::class, 'microsoft_access_level', null],
        "\0".parent::class."\0".'microsoft_excel_level' => [parent::class, 'microsoft_excel_level', null],
        "\0".parent::class."\0".'microsoft_oneNote_level' => [parent::class, 'microsoft_oneNote_level', null],
        "\0".parent::class."\0".'microsoft_outlook_level' => [parent::class, 'microsoft_outlook_level', null],
        "\0".parent::class."\0".'microsoft_powerPoint_level' => [parent::class, 'microsoft_powerPoint_level', null],
        "\0".parent::class."\0".'microsoft_project_level' => [parent::class, 'microsoft_project_level', null],
        "\0".parent::class."\0".'microsoft_publisher_level' => [parent::class, 'microsoft_publisher_level', null],
        "\0".parent::class."\0".'microsoft_visio_level' => [parent::class, 'microsoft_visio_level', null],
        "\0".parent::class."\0".'microsoft_word_level' => [parent::class, 'microsoft_word_level', null],
        "\0".parent::class."\0".'otherNotInfoSkills' => [parent::class, 'otherNotInfoSkills', null],
        "\0".parent::class."\0".'other_language_name' => [parent::class, 'other_language_name', null],
        "\0".parent::class."\0".'other_language_reading_level' => [parent::class, 'other_language_reading_level', null],
        "\0".parent::class."\0".'other_language_speaking_level' => [parent::class, 'other_language_speaking_level', null],
        "\0".parent::class."\0".'other_language_writing_level' => [parent::class, 'other_language_writing_level', null],
        "\0".parent::class."\0".'other_skills' => [parent::class, 'other_skills', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'english_reading_level' => [parent::class, 'english_reading_level', null],
        'english_speaking_level' => [parent::class, 'english_speaking_level', null],
        'english_writing_level' => [parent::class, 'english_writing_level', null],
        'french_reading_level' => [parent::class, 'french_reading_level', null],
        'french_speaking_level' => [parent::class, 'french_speaking_level', null],
        'french_writing_level' => [parent::class, 'french_writing_level', null],
        'id' => [parent::class, 'id', null],
        'malagasy_reading_level' => [parent::class, 'malagasy_reading_level', null],
        'malagasy_speaking_level' => [parent::class, 'malagasy_speaking_level', null],
        'malagasy_writing_level' => [parent::class, 'malagasy_writing_level', null],
        'microsoft_access_level' => [parent::class, 'microsoft_access_level', null],
        'microsoft_excel_level' => [parent::class, 'microsoft_excel_level', null],
        'microsoft_oneNote_level' => [parent::class, 'microsoft_oneNote_level', null],
        'microsoft_outlook_level' => [parent::class, 'microsoft_outlook_level', null],
        'microsoft_powerPoint_level' => [parent::class, 'microsoft_powerPoint_level', null],
        'microsoft_project_level' => [parent::class, 'microsoft_project_level', null],
        'microsoft_publisher_level' => [parent::class, 'microsoft_publisher_level', null],
        'microsoft_visio_level' => [parent::class, 'microsoft_visio_level', null],
        'microsoft_word_level' => [parent::class, 'microsoft_word_level', null],
        'otherNotInfoSkills' => [parent::class, 'otherNotInfoSkills', null],
        'other_language_name' => [parent::class, 'other_language_name', null],
        'other_language_reading_level' => [parent::class, 'other_language_reading_level', null],
        'other_language_speaking_level' => [parent::class, 'other_language_speaking_level', null],
        'other_language_writing_level' => [parent::class, 'other_language_writing_level', null],
        'other_skills' => [parent::class, 'other_skills', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
